import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { Text } from "@/components/Text";
import { Navbar } from "@/components/Navbar";

export default function Agradecimientos() {
  return (
    <>
      <Head>
        <title>Unshaping masculinity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pb-16">
        <Navbar page="agradecimientos" />
        <div className="w-full flex items-center justify-center mt-20">
          <Image
            src="/images/agradecimientos.png"
            alt="Mano sosteniendo un corazon"
            width={150}
            height={200}
          />
        </div>
        <Text as="header" className="text-center mt-4">
          Agradecimientos
        </Text>
        <div className="flex flex-col items-center gap-8 mt-4">
          <div className="flex flex-col items-center justify-center">
            <Image
              src="/images/logo.png"
              alt="Logo de Unshaping Masculinity"
              width={136}
              height={136}
            />
            <Text as="subheader" className="text-gray-400 text-center">
              Desarrollo de proyecto
            </Text>
          </div>
          <div className="flex flex-col items-center justify-center">
            <Image
              src="/images/global-shapers.png"
              alt="Logo de Global Shapers"
              className="mb-2"
              width={100}
              height={100}
            />
            <Text as="subheader" className="text-gray-400 text-center">
              Iniciativa
            </Text>
          </div>
          <Link href="https://adrojo.art" target="_blank">
            <div className="flex flex-col items-center justify-center">
              <Image
                src="/images/bubbles.png"
                alt="Burbuja de colores, logo de ad_rojo"
                width={136}
                height={136}
              />
              <Text as="paragraph" className="text-gray-700 text-center">
                ad_rojo
              </Text>
              <Text as="subheader" className="text-gray-400 text-center">
                desarrollo web
              </Text>
            </div>
          </Link>
          <div className="flex flex-col items-center justify-center">
            <Image
              src="/images/ledieguex.png"
              alt="Agradecimientos"
              width={136}
              height={136}
            />
            <Text as="paragraph" className="text-gray-700 text-center">
              Ledieguex
            </Text>
            <Text as="subheader" className="text-gray-400 text-center">
              Ilustración
            </Text>
          </div>
        </div>
      </main>
    </>
  );
}
