import { useState } from "react";

import Head from "next/head";
import { Inter } from "next/font/google";

import Icon from "react-material-symbols/rounded";

const inter = Inter({ subsets: ["latin"] });

import { Text } from "@/components/Text";
import { BackNavBar } from "@/components/BackNavBar";
import { Button } from "@/components/Button";
import { Radio } from "@/components/Radio";

export default function Home() {
  const [selected, setSelected] = useState<string>("zero");

  function saveSelected() {
    sessionStorage.setItem("level", selected);
    location.href = "/game";
  }

  return (
    <>
      <Head>
        <title>Unshaping masculinity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center gap-10 px-2">
        <BackNavBar />
        <div className="flex flex-col px-4 gap-2">
          <Text as="header">La caja de preguntas</Text>
          <Text as="paragraph">
            Para elegir el mejor set de preguntas para esta ocasión quisiéramos
            que eligieras la opción con la que te sientes más cercano acerca de
            tu masculinidad.
          </Text>
        </div>
        <div className="flex flex-col gap-2 items-stretch w-full px-4">
          <Radio
            selected={selected}
            setSelected={setSelected}
            name="status"
            id="first"
            className="flex flex-row"
          >
            <Icon icon="eco" size={24} />
            <Text as="paragraph">Nunca la he cuestionado</Text>
          </Radio>
          <Radio
            selected={selected}
            setSelected={setSelected}
            name="status"
            id="second"
            className="flex flex-row"
          >
            <Icon icon="spa" size={24} />
            <Text as="paragraph">La he llegado a cuestionar</Text>
          </Radio>
          <Radio
            selected={selected}
            setSelected={setSelected}
            name="status"
            id="third"
            className="flex flex-row"
          >
            <Icon icon="filter_vintage" size={24} />
            <Text as="paragraph">La suelo cuestionar amenudo</Text>
          </Radio>
        </div>
        <Button
          onClick={saveSelected}
          variant={selected == "zero" ? "disabled" : "default"}
        >
          Continuar
        </Button>
      </main>
    </>
  );
}
