import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

import { Navbar } from "@/components/Navbar";
import { Text } from "@/components/Text";
import { Button } from "@/components/Button";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Unshaping masculinity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pb-8">
        <Navbar page="home" />
        <div className="px-4">
          <Image
            src="/images/portada.png"
            alt="A man getting out of a box with a question mark in it"
            width={100}
            height={100}
            layout="responsive"
          />
          <div
            className="flex flex-col gap-6 items-center -mt-10
        "
          >
            <div className="flex flex-col gap-2 px-2">
              <Text as="header" className="text-center">
                La Caja de preguntas
              </Text>
              <Text as="paragraph" className="text-center">
                La &quot;man box&quot; o caja de hombres es una construcción
                cultural que impone una serie de normas y expectativas sobre
                cómo deben comportarse los hombres. Estas normas suelen incluir
                la idea de que los hombres deben ser fuertes, dominantes y no
                mostrar emociones o vulnerabilidad.
                <br></br>
                <br></br>Esta caja de hombres limita la expresión y el
                desarrollo personal de los hombres, y también puede conducir a
                la violencia de género.
                <br></br>
                <br></br>A continuación nos proponemos cuestionar la
                masculinidad hegemónica y reflexionar sobre cómo podemos
                deshacernos de las cajas que encierran un único modelo de
                masculinidad, así intentar crear una sociedad más justa e
                igualitaria.
                <br></br>
                <br></br>Da clic en continuar para ver las preguntas.
              </Text>
            </div>
            <Link href="/deck">
              <Button className="ml-2" variant="default">
                Continuar
              </Button>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
