import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

import { Navbar } from "@/components/Navbar";
import { Text } from "@/components/Text";
import { Button } from "@/components/Button";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Unshaping masculinity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pb-8">
        <Navbar page="home" />
        <div className="px-4">
          <Image
            className="mt-8"
            src="/images/portada.png"
            alt="A man getting out of a box with a question mark in it"
            width={100}
            height={100}
            layout="responsive"
          />
          <div
            className="flex flex-col gap-6 items-start
        "
          >
            <div className="flex flex-col gap-2 px-2">
              <Text as="header">La caja de preguntas</Text>
              <Text as="paragraph">
                A continuación encontrarás una serie de preguntas que al
                hacérnoslas pueden ayudarnos a cuestionarnos qué significa ser
                un hombre hoy en día y cómo podemos
              </Text>
            </div>
            <Link href="/deck">
              <Button className="ml-2" variant="default">
                Continuar
              </Button>
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
