import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { Text } from "@/components/Text";
import { Navbar } from "@/components/Navbar";
import { Button } from "@/components/Button";

export default function Agradecimientos() {
  return (
    <>
      <Head>
        <title>Unshaping masculinity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pb-16 px-2 flex flex-col items-stretch gap-6">
        <Navbar page="retroalimentacion" />
        <div className="w-full flex items-center justify-center mt-20">
          <Image
            src="/images/feedback.png"
            alt="Mano sosteniendo un corazon"
            width={150}
            height={200}
          />
        </div>
        <div className="flex flex-col gap-8 px-4 items-center">
          <div className="flex flex-col gap-4">
            <Text as="header" className="text-center mt-4">
              Retroalimentación
            </Text>
            <Text as="paragraph" className="text-center">
              ¿Tienes ideas de cómo poder mejorar las preguntas que hay en este
              proyecto para acercanos a masculinidades más diversas?
              <br />
              <br />
              ¿Quieres dejarnos con tus comentarios?
              <br />
              <br />
              Llena el formulario de a continuación
            </Text>
          </div>
          <Link href="https://forms.gle/5ywL23d4kVB4MJ889" target="_blank">
            <Button variant="default">Formulario</Button>
          </Link>
        </div>
      </main>
    </>
  );
}
